<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Lead;

class McKinneyLeadsSeeder extends Seeder
{
    public function run()
    {
        Lead::create([
            'id' => Str::uuid(),
            'name' => '1-800-GOT-JUNK? Dallas Central',
            'reviews' => null,
            'address' => null,
            'website' => 'https://www.1800gotjunk.com/us_en/locations/junk-removal-dallas/us03049?utm_source=googleplus&utm_medium=maps&utm_campaign=dallascentral',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => '1-800-GOT-JUNK? Dallas Central',
            'reviews' => null,
            'address' => null,
            'website' => 'https://www.1800gotjunk.com/us_en/locations/junk-removal-dallas/us03049?utm_source=googleplus&utm_medium=maps&utm_campaign=dallascentral',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'All My Sons Moving & Storage',
            'reviews' => null,
            'address' => null,
            'website' => 'https://www.allmysons.com/texas/mckinney/index.aspx?utm_source=GMBlisting&utm_medium=organic&phone=972-848-6007',
            'phone' => '· (972) 848-6007',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'All My Sons Moving & Storage',
            'reviews' => null,
            'address' => null,
            'website' => 'https://www.allmysons.com/texas/mckinney/index.aspx?utm_source=GMBlisting&utm_medium=organic&phone=972-848-6007',
            'phone' => '· (972) 848-6007',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Speedy Junk Removal',
            'reviews' => -1,
            'address' => null,
            'website' => null,
            'phone' => '· (214) 994-8385',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Getitgone junk removal',
            'reviews' => -1,
            'address' => null,
            'website' => 'https://getitgonejunkremoval.net/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Jack\'s Tool Box Demolition & Junk Removal',
            'reviews' => -1,
            'address' => null,
            'website' => 'https://jacks-tool-box-demolition-junk-removal.ueniweb.com/?utm_campaign=gmb',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Smash My Trash',
            'reviews' => -1,
            'address' => null,
            'website' => 'https://smashmytrash.com/tx/mckinney-sherman/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'North Texas Property Works',
            'reviews' => -1,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Doo Dispatch',
            'reviews' => -1,
            'address' => null,
            'website' => 'https://www.doodispatch.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Integrity Trailers & Junk Removal',
            'reviews' => -1,
            'address' => null,
            'website' => 'https://rentme.integritylps.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Instant Valet',
            'reviews' => -1,
            'address' => null,
            'website' => 'https://www.instantvaletsvc.com/',
            'phone' => '· (469) 803-0665',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Getitgone junk removal',
            'reviews' => -1,
            'address' => null,
            'website' => 'https://getitgonejunkremoval.net/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Jack\'s Tool Box Demolition & Junk Removal',
            'reviews' => -1,
            'address' => null,
            'website' => 'https://jacks-tool-box-demolition-junk-removal.ueniweb.com/?utm_campaign=gmb',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Smash My Trash',
            'reviews' => -1,
            'address' => null,
            'website' => 'https://smashmytrash.com/tx/mckinney-sherman/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'JC Junk Crew',
            'reviews' => -2,
            'address' => null,
            'website' => 'https://jcjunkcrew.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Goodbye Junk DFW',
            'reviews' => -2,
            'address' => null,
            'website' => 'https://goodbyejunkdfw.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Junk Shot Junk Removal',
            'reviews' => -2,
            'address' => null,
            'website' => 'https://www.junkshotapp.com/north-dallas/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Champs Junk Removal',
            'reviews' => -2,
            'address' => null,
            'website' => 'https://champjunkremoval.com/?utm_source=omg-gbp&utm_medium=webclick',
            'phone' => '· (972) 945-5865',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Towawaytoday - Junk Car Buying Service',
            'reviews' => -2,
            'address' => null,
            'website' => 'https://towawaytoday.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => '2 Chicks & A Trailer',
            'reviews' => -2,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Champs Junk Removal',
            'reviews' => -2,
            'address' => null,
            'website' => 'https://champjunkremoval.com/?utm_source=omg-gbp&utm_medium=webclick',
            'phone' => '· (972) 945-5865',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Junk Guys Mckinney TX',
            'reviews' => -3,
            'address' => null,
            'website' => 'https://www.junkguysmckinneytx.com/',
            'phone' => '· (469) 422-6100',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'NTX Junk Haul & Services',
            'reviews' => -3,
            'address' => null,
            'website' => 'https://www.ntxjunkhaulservices.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Junk Dumped - Junk Removal Allen',
            'reviews' => -3,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'AHaulAwayTX',
            'reviews' => -3,
            'address' => null,
            'website' => null,
            'phone' => '· (469) 215-7315',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'SBN Junk Removal Mckinney Pros',
            'reviews' => -3,
            'address' => null,
            'website' => 'https://ezhaulingandjunkremoval.com/junk-removal-mckinney/',
            'phone' => '· (469) 815-7317',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Junk Dumped - Junk Removal Allen',
            'reviews' => -3,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'AHaulAwayTX',
            'reviews' => -3,
            'address' => null,
            'website' => null,
            'phone' => '· (469) 215-7315',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'USS Junk',
            'reviews' => -5,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'USS Junk',
            'reviews' => -5,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Southern Junk Removal',
            'reviews' => -6,
            'address' => null,
            'website' => 'https://southernjunkremoval.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Southern Junk Removal',
            'reviews' => -6,
            'address' => null,
            'website' => 'https://southernjunkremoval.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Roberto Junk Removal',
            'reviews' => -6,
            'address' => null,
            'website' => null,
            'phone' => '· (972) 903-6391',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Long Horn Trash & Junk Removal',
            'reviews' => -6,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Roberto Junk Removal',
            'reviews' => -6,
            'address' => null,
            'website' => null,
            'phone' => '· (972) 903-6391',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Long Horn Trash & Junk Removal',
            'reviews' => -6,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Dallas Junk Guys',
            'reviews' => -7,
            'address' => null,
            'website' => 'https://www.dallasjunkguys.com/',
            'phone' => '· (469) 884-0070',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'My valet and junk removal',
            'reviews' => -8,
            'address' => null,
            'website' => 'https://myvaletanjunkremoval.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'OCHOA\'S JUNK SOLUTIONS LLC',
            'reviews' => -8,
            'address' => null,
            'website' => 'https://www.ochoasjunksolutions.com/',
            'phone' => '· (945) 942-7255',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'POOP 911 Rockwall',
            'reviews' => -8,
            'address' => null,
            'website' => 'https://www.poop911.com/service-area/texas/rockwall-pooper-scooper-service/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Landslide Removal LLC - Junk Removal',
            'reviews' => -8,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'My valet and junk removal',
            'reviews' => -8,
            'address' => null,
            'website' => 'https://myvaletanjunkremoval.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'OCHOA\'S JUNK SOLUTIONS LLC',
            'reviews' => -8,
            'address' => null,
            'website' => 'https://www.ochoasjunksolutions.com/',
            'phone' => '· (945) 942-7255',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'M&I Express Junk Removal',
            'reviews' => -10,
            'address' => null,
            'website' => null,
            'phone' => '· (972) 302-1423',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'NTX Junk Pros',
            'reviews' => -11,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'S&M Removal Services',
            'reviews' => -11,
            'address' => null,
            'website' => null,
            'phone' => '· (214) 870-6867',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'S&M Removal Services',
            'reviews' => -11,
            'address' => null,
            'website' => null,
            'phone' => '· (214) 870-6867',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Anything Goes Junk Removal',
            'reviews' => -12,
            'address' => null,
            'website' => 'https://anythinggoesjunk.com/',
            'phone' => '· (214) 726-6683',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Junk Solutions',
            'reviews' => -15,
            'address' => null,
            'website' => 'https://junksolutionsntx.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Good Bull Dumpster Company',
            'reviews' => -16,
            'address' => null,
            'website' => 'https://www.goodbulldumpsterrental.com/?utm_campaign=gmb',
            'phone' => '· (469) 461-7685',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Champs Junk Removal',
            'reviews' => -18,
            'address' => null,
            'website' => 'https://champjunkremoval.com/',
            'phone' => '· (469) 767-5919',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'DoodyCalls Pet Waste Removal',
            'reviews' => -18,
            'address' => null,
            'website' => 'https://www.doodycalls.com/dallas-fort-worth/',
            'phone' => '· (214) 273-6954',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'DoodyCalls Pet Waste Removal',
            'reviews' => -18,
            'address' => null,
            'website' => 'https://www.doodycalls.com/dallas-fort-worth/',
            'phone' => '· (214) 273-6954',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Renegade Removal',
            'reviews' => -19,
            'address' => null,
            'website' => 'http://renegade-removal.com/',
            'phone' => '· (214) 254-1657',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'HKLO Hauling and Junk Removal',
            'reviews' => -22,
            'address' => null,
            'website' => null,
            'phone' => '· (214) 225-6354',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Genie Junk Removal LLC',
            'reviews' => -24,
            'address' => null,
            'website' => 'https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwja4fWYiseNAxUkoloFHYxdICUYABAAGgJ2dQ&co=1&gclid=CjwKCAjw6NrBBhB6EiwAvnT_rkKcpmQIIKmT6BwkCHw10U64bW44tKpznTTkx_KUFK-gPgZXm-mLoBoC2A8QAvD_BwE&ohost=www.google.com&cid=CAESV-D2k_HniaSUh6KEAzO9Cm-DHnZNYaRPpBmjzi11Jyg1rulZ0Nmh1aBFIov4ZIhb9HXmq6kaRthqJyvwmmzwQDMpYoZpU4HXPfNn4rEU5f7RjIaIOORiPg&category=acrcp_v1_40&sig=AOD64_33OMQLBJn2IR2C7295lzETobVvlA&q=&ctype=99&ved=2ahUKEwi7ke-YiseNAxXRSzABHcBUAdwQhKwBegQIFBAP&adurl=',
            'phone' => 'Open',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Grab N Go Junk Removal and Demolition',
            'reviews' => -24,
            'address' => null,
            'website' => 'https://grabngojunkremoval.net/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Genie Junk Removal LLC',
            'reviews' => -24,
            'address' => null,
            'website' => 'https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwiPru2hiseNAxVmpFoFHd4bJS4YABAAGgJ2dQ&co=1&gclid=CjwKCAjw6NrBBhB6EiwAvnT_rgZjSo60onNKhmLfOcVjG3mKKSRCWEsWLWfOf9OVbojbdBB2AtoxrxoC_esQAvD_BwE&ohost=www.google.com&cid=CAESV-D2eZCWxY5eTRf4u8FUuHIK_TM_gVH7DeCiannr80DeIl27Q0DXX_b0m_CfjdtOcL0kOXL55PvE_7cIhLFbcszQDaJBjXnwpi84sfwXb3RaOv6jUV0k2g&category=acrcp_v1_40&sig=AOD64_1pglfZZbVWkwgp3CPNS9NTRIqtwA&q=&ctype=99&ved=2ahUKEwjp1uehiseNAxUWSDABHc-7EXo4FBCErAF6BAgKEA8&adurl=',
            'phone' => 'Open',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Grab N Go Junk Removal and Demolition',
            'reviews' => -24,
            'address' => null,
            'website' => 'https://grabngojunkremoval.net/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Genie Junk Removal LLC',
            'reviews' => -24,
            'address' => null,
            'website' => 'https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwjUveeiiseNAxW4nVoFHacTEZsYABAAGgJ2dQ&co=1&gclid=CjwKCAjw6NrBBhB6EiwAvnT_rmFJlUerrdGswwURAwK-sZZusEtpxBvqPoTkChWbF3CoX9kVxf3rbxoCRUYQAvD_BwE&ohost=www.google.com&cid=CAESV-D2xRlZ2LxWSiOhJwMyK3gxxtymektOJRF8L-9KB-dP21cSOZJzZOqQ4rOYvG0MG_Kn-TNhV8o909n4HEvYjeq_vF2T01vU4TjqmOWj1taf3zkwIYtfdw&category=acrcp_v1_40&sig=AOD64_1x6BpS5VjHLh8PTmzBBCo-yqCJXA&q=&ctype=99&ved=2ahUKEwji2-GiiseNAxUmRjABHaMaASY4KBCErAF6BAgOEA8&adurl=',
            'phone' => 'Open',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Genie Junk Removal LLC',
            'reviews' => -24,
            'address' => null,
            'website' => 'https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwjN2tajiseNAxUkn1oFHZ0lJ10YABAAGgJ2dQ&co=1&gclid=CjwKCAjw6NrBBhB6EiwAvnT_ruJf-Lbz1_ZWAS9G7x1EGsKPMD6chqTTzRib61a4RGBsqIGDafbbnBoCroQQAvD_BwE&ohost=www.google.com&cid=CAESV-D2dvryUxKqEm1l9QD0n9T5A3vzVaY5f10iWoUDzHgoyo22EaPSbUaohg0wCddFkHvHPta3kfnIGsHcYSWFam9G4dQkZbhX6ffXo6XJDC_eFYt4XeHx1Q&category=acrcp_v1_40&sig=AOD64_0Ql8oToA7k9P1yfQ6ta39CFX01RA&q=&ctype=99&ved=2ahUKEwjNptCjiseNAxXLRDABHbP5OMc4PBCErAF6BAgNEA8&adurl=',
            'phone' => 'Open',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Genie Junk Removal LLC',
            'reviews' => -24,
            'address' => null,
            'website' => 'https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwi3r8mkiseNAxVNgFoFHfIeEwQYABAAGgJ2dQ&co=1&gclid=CjwKCAjw6NrBBhB6EiwAvnT_rqencVujcUWdvkkTos0C-sEHnN1usLZjaYisOOOGZXGLWH7R8cdHZRoCPJoQAvD_BwE&ohost=www.google.com&cid=CAESV-D2VXq9mu9zSNF-P3w8w5XG0prw0IF0EjQ6--SeEAi7AhBuII0kWt2RxogZOTNlydNwb6cYLp9WEnMgMDjPMOthbHsh2xYMywwja1dQDNKMwUg9iCoZ5g&category=acrcp_v1_40&sig=AOD64_0z-1fK9yGPtEUV8vR3H6jASCO5iw&q=&ctype=99&ved=2ahUKEwjtpsOkiseNAxXeTTABHTFbAQI4KBCErAF6BAgQEA8&adurl=',
            'phone' => 'Open',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Easy Pickup Junk Removal',
            'reviews' => -26,
            'address' => null,
            'website' => 'http://www.easypickupjunkremoval.com/',
            'phone' => '· (510) 637-9330',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Rubbish Works Junk Removal of Frisco',
            'reviews' => -28,
            'address' => null,
            'website' => 'https://rubbishworks.com/frisco',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Texas Delta Hauling & Junk Removal',
            'reviews' => -31,
            'address' => null,
            'website' => 'http://txdeltajunkremoval.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Texas Delta Hauling & Junk Removal',
            'reviews' => -31,
            'address' => null,
            'website' => 'http://txdeltajunkremoval.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'McKinney Junk Car For Cash',
            'reviews' => -36,
            'address' => null,
            'website' => 'https://mckinneyjunkcarforcash.com/',
            'phone' => '· (972) 934-6204',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'McKinney Junk Car For Cash',
            'reviews' => -36,
            'address' => null,
            'website' => 'https://mckinneyjunkcarforcash.com/',
            'phone' => '· (972) 934-6204',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Spaulding Decon - Hoarding & Crime Scene Cleanup Flower Mound',
            'reviews' => -42,
            'address' => null,
            'website' => 'https://www.spauldingdecon.com/locations/texas/flower-mound?utm_source=gmb&utm_medium=organic&utm_campaign=gmb-listing',
            'phone' => '· (214) 833-5827',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'CR Superior Services Junk Removal & Fence Repairs',
            'reviews' => -60,
            'address' => null,
            'website' => 'http://crjunkremoval.com/',
            'phone' => '· (469) 728-4700',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'JunkDumped',
            'reviews' => -66,
            'address' => null,
            'website' => null,
            'phone' => '· (469) 998-6181',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Gladiator Dumpsters',
            'reviews' => -69,
            'address' => null,
            'website' => 'https://www.gladiatordumpsters.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'JDog Junk Removal and Hauling Frisco',
            'reviews' => -74,
            'address' => null,
            'website' => 'https://www.jdog.com/',
            'phone' => '· (469) 735-9227',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'JDog Junk Removal and Hauling Frisco',
            'reviews' => -74,
            'address' => null,
            'website' => 'https://www.jdog.com/',
            'phone' => '· (469) 735-9227',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Diamond Demo & Junk Removal',
            'reviews' => -74,
            'address' => null,
            'website' => 'http://diamonddemoandjunkremoval.com/',
            'phone' => '· (214) 548-2972',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'K. Davis Moving',
            'reviews' => -81,
            'address' => null,
            'website' => 'https://kdavismoving.com/',
            'phone' => '· (469) 450-2143',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Trashformers Roll-Off Dumpster Rental',
            'reviews' => -86,
            'address' => null,
            'website' => 'https://www.trashformersdumpsters.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Trashformers Roll-Off Dumpster Rental',
            'reviews' => -86,
            'address' => null,
            'website' => 'https://www.trashformersdumpsters.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Junk Guys Frisco',
            'reviews' => -88,
            'address' => null,
            'website' => 'http://www.junkguysfrisco.com/',
            'phone' => '· (214) 682-5598',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'ABC-A Better Choice Moving Services',
            'reviews' => -94,
            'address' => null,
            'website' => 'https://abetterchoicemoving.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Haul It Off Lopez',
            'reviews' => -122,
            'address' => null,
            'website' => 'https://haulitofflopez.com/',
            'phone' => '· (469) 412-2848',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'JDog Junk Removal & Hauling North Dallas',
            'reviews' => -160,
            'address' => null,
            'website' => 'http://jdogjunkremoval.com/',
            'phone' => '· (214) 605-3336',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Derrick\'s Disposal',
            'reviews' => -162,
            'address' => null,
            'website' => 'http://derricksremoval.com/',
            'phone' => '· (214) 901-8557',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Celina Junk Removal',
            'reviews' => -169,
            'address' => null,
            'website' => 'http://celinajunkremoval.com/',
            'phone' => '· (682) 552-6013',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Custer Transfer Station',
            'reviews' => -211,
            'address' => null,
            'website' => 'https://www.ntmwd.com/facilities/',
            'phone' => '· (972) 727-6341',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Anything Goes Moving',
            'reviews' => -217,
            'address' => null,
            'website' => 'https://www.agmoving.com/',
            'phone' => '· (972) 362-5613',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Hernandez Auto Salvage',
            'reviews' => -261,
            'address' => null,
            'website' => null,
            'phone' => '· (972) 635-3186',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'The Junkluggers of Collin County',
            'reviews' => -291,
            'address' => null,
            'website' => 'https://www.junkluggers.com/collin-county/?utm_source=google&utm_medium=gbp',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'All Star Junk Hauling Services',
            'reviews' => -316,
            'address' => null,
            'website' => 'http://www.allstarjunkhauling.com/',
            'phone' => '· (972) 449-7711',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Junk Queen TX',
            'reviews' => -327,
            'address' => null,
            'website' => 'https://junkqueentx.com/',
            'phone' => '· (469) 909-7241',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'The Move Pros',
            'reviews' => -433,
            'address' => null,
            'website' => 'http://texasmovepros.com/',
            'phone' => '· (214) 991-1295',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Junk Quest',
            'reviews' => -537,
            'address' => null,
            'website' => 'https://www.junkquestdfw.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Stand Up Guys Junk Removal',
            'reviews' => -555,
            'address' => null,
            'website' => 'https://standupguys.com/texas/dallas-junk-removal/?utm_source=gbp-dallas&utm_medium=organic&utm_campaign=gbp-listing-main',
            'phone' => '· (214) 299-7419',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Two Men and a Truck Moving',
            'reviews' => -694,
            'address' => null,
            'website' => 'https://twomenandatruck.com/movers/tx/dallas/mckinney?utm_source=google&utm_medium=organic&utm_campaign=gmb',
            'phone' => '· (469) 523-4772',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Two Men and a Truck Moving',
            'reviews' => -694,
            'address' => null,
            'website' => 'https://twomenandatruck.com/movers/tx/dallas/mckinney?utm_source=google&utm_medium=organic&utm_campaign=gmb',
            'phone' => '· (469) 523-4772',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'WASTE CONNECTIONS MCKINNEY',
            'reviews' => -736,
            'address' => null,
            'website' => 'https://www.wasteconnections.com/mckinney',
            'phone' => '· (469) 452-8000',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'WASTE CONNECTIONS MCKINNEY',
            'reviews' => -736,
            'address' => null,
            'website' => 'https://www.wasteconnections.com/mckinney',
            'phone' => '· (469) 452-8000',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'nan',
            'reviews' => null,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'nan',
            'reviews' => null,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Haul Zilla Junk Removal',
            'reviews' => null,
            'address' => null,
            'website' => null,
            'phone' => '· (469) 238-9760',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'USS Junk Removal',
            'reviews' => null,
            'address' => null,
            'website' => null,
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Junk Liberators',
            'reviews' => null,
            'address' => null,
            'website' => 'http://junkliberators.com/',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Junk Doctor',
            'reviews' => null,
            'address' => null,
            'website' => null,
            'phone' => '· (214) 335-3681',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Harrell Dump Services',
            'reviews' => null,
            'address' => null,
            'website' => 'https://www.harrelldumpservices.com/en-us/#contact',
            'phone' => null,
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Prestige Junk Removal Pros',
            'reviews' => null,
            'address' => null,
            'website' => 'https://ezhaulingandjunkremoval.com/mckinney/',
            'phone' => '· (972) 449-9082',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
        Lead::create([
            'id' => Str::uuid(),
            'name' => 'Haul Zilla Junk Removal',
            'reviews' => null,
            'address' => null,
            'website' => null,
            'phone' => '· (469) 238-9760',
            'city' => 'McKinney, TX',
            'contacted' => false,
            'notes' => null,
        ]);
    }
}